// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCimFHFMDXJloPvjsgMolXdrzMBpE0aIUg',
    appId: '1:230945599038:web:a78dcc75bc026570b4ab6f',
    messagingSenderId: '230945599038',
    projectId: 'flutter-crud-b42f2',
    authDomain: 'flutter-crud-b42f2.firebaseapp.com',
    storageBucket: 'flutter-crud-b42f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVWDIKuyThwEu3WJqsikoV7ZsTx_UfkEA',
    appId: '1:230945599038:android:ee895ff355823530b4ab6f',
    messagingSenderId: '230945599038',
    projectId: 'flutter-crud-b42f2',
    storageBucket: 'flutter-crud-b42f2.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCimFHFMDXJloPvjsgMolXdrzMBpE0aIUg',
    appId: '1:230945599038:web:4e9463046e1c66b9b4ab6f',
    messagingSenderId: '230945599038',
    projectId: 'flutter-crud-b42f2',
    authDomain: 'flutter-crud-b42f2.firebaseapp.com',
    storageBucket: 'flutter-crud-b42f2.appspot.com',
  );
}
